---
# Playbook: switch_backup.yml
# Description: Backup network switch configurations - uses external script for Git operations

- name: Backup Network Switch Configurations
  hosts: switch_stack_B_A
  gather_facts: false
  vars:
    backup_path: "/var/lib/awx/projects/su_network_backup/kantra/building_A/stack"

  tasks:
    - name: Create backup directory if it doesn't exist
      file:
        path: "{{ backup_path }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Backup Cisco IOS switch configurations
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: "{{ backup_path }}"
      register: backup_results

    - name: Run external Git push script
      shell: /var/lib/awx/projects/push_configs.sh
      delegate_to: localhost
      run_once: true
