---
# Playbook: switch_backup.yml
# Description: Back up switch configurations and push them to GitHub
# Used with inventory "Cisco_ios_inventory" and group "switch_stack_B_A"

- name: Backup Network Switch Configurations
  hosts: switch_stack_B_A
  gather_facts: false
  vars:
    temp_backup_path: "/tmp/switch_backups"
    host_backup_path: "/var/lib/awx/projects/switch_backups"

  tasks:
    - name: Ensure temporary backup directory exists
      file:
        path: "{{ temp_backup_path }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: yes

    - name: Ensure persistent host backup directory exists
      file:
        path: "{{ host_backup_path }}"
        state: directory
        mode: '0777'  # Avoid permission issues
      delegate_to: localhost
      run_once: true
      become: yes

    - name: Backup Cisco IOS switch configurations
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: "{{ temp_backup_path }}"
      register: backup_results

    - name: Display backup path
      debug:
        msg: "Backup saved to: {{ backup_results.backup_path }}"
      when: backup_results is defined

    - name: Copy backup files to persistent storage
      copy:
        src: "{{ temp_backup_path }}/{{ inventory_hostname }}.cfg"
        dest: "{{ host_backup_path }}/{{ inventory_hostname }}.cfg"
        mode: '0644'
        remote_src: yes
      delegate_to: localhost
      become: yes
      when: backup_results is defined and backup_results.backup_path is defined

    - name: Verify backup files exist in persistent storage
      stat:
        path: "{{ host_backup_path }}/{{ inventory_hostname }}.cfg"
      register: file_check
      delegate_to: localhost
      become: yes

    - name: Show existing backup files
      debug:
        msg: "Existing backup files: {{ host_backup_path }}"
      delegate_to: localhost
      become: yes

    - name: Fail if no backup files were found
      fail:
        msg: "No backup files found in {{ host_backup_path }}"
      when: file_check.stat.exists == false

    - name: Ensure GitHub push script is in place
      copy:
        dest: "/var/lib/awx/projects/push_configs.sh"
        mode: '0755'
        content: |
          #!/bin/bash
          set -e
          
          BACKUP_PATH="/var/lib/awx/projects/switch_backups"
          GIT_USER="salwan.mohamed"
          GIT_EMAIL="salwan.mohamed@su.edu.eg"
          GIT_TOKEN="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"
          GIT_REPO="networksu/su_network_backup"
          LOG_FILE="/var/lib/awx/projects/github_push.log"

          echo "==== Starting GitHub push script ====" > $LOG_FILE
          
          cd $BACKUP_PATH || { echo "ERROR: Cannot access $BACKUP_PATH" | tee -a $LOG_FILE; exit 1; }
          echo "Current directory: $(pwd)" >> $LOG_FILE
          
          if [ ! -d ".git" ]; then
            echo "Initializing new Git repository" | tee -a $LOG_FILE
            git init
            git branch -m master main
            git remote add origin "https://$GIT_USER:$GIT_TOKEN@github.com/$GIT_REPO.git"
          fi

          echo "Setting up Git configurations" | tee -a $LOG_FILE
          git config user.name "$GIT_USER"
          git config user.email "$GIT_EMAIL"

          echo "Adding backup files to Git" | tee -a $LOG_FILE
          git add -A
          git commit -m "Switch configurations - $(date +%Y%m%d_%H%M%S)" || echo "Nothing to commit" >> $LOG_FILE

          echo "Fetching latest updates from GitHub" | tee -a $LOG_FILE
          git fetch origin main
          git reset --hard origin/main

          echo "Pushing to GitHub..." | tee -a $LOG_FILE
          git push -u origin main --force || { echo "ERROR: Git push failed" | tee -a $LOG_FILE; exit 1; }

          echo "Backup and push completed successfully" | tee -a $LOG_FILE
      delegate_to: localhost
      run_once: true
      become: yes

    - name: Run GitHub push script
      shell: "/var/lib/awx/projects/push_configs.sh"
      delegate_to: localhost
      run_once: true
      become: yes
      register: push_script_result
      failed_when: "'ERROR' in push_script_result.stdout"

    - name: Show push script log if exists
      shell: "cat /var/lib/awx/projects/github_push.log || echo 'Log file not found'"
      delegate_to: localhost
      run_once: true
      register: git_log
      become: yes
      ignore_errors: yes

    - name: Display git push log
      debug:
        var: git_log.stdout_lines
      run_once: true
