---
# Playbook: switch_backup.yml 
# Description: Backs up switch configurations and commits to GitHub
# For use with existing inventory "Cisco_ios_invetory" and group "switch_stack_B_A"

- name: Backup Network Switch Configurations
  hosts: switch_stack_B_A
  gather_facts: false
  vars:
    backup_path: "/var/lib/awx/projects/switch_backups"

  tasks:
    - name: Create backup directory if it doesn't exist
      file:
        path: "{{ backup_path }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: yes

    - name: Backup Cisco IOS switch configurations
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: "{{ backup_path }}"
      register: backup_results

    - name: Show backup results
      debug:
        var: backup_results
      when: backup_results is defined

    - name: Run GitHub push script
      shell: /var/lib/awx/projects/push_configs.sh
      delegate_to: localhost
      run_once: true
      become: yes
