---
# Playbook: switch_backup_with_post.yml 
# This playbook backs up switches and then runs a post-job command to push to GitHub

- name: Backup Network Switch Configurations
  hosts: switch_stack_B_A
  gather_facts: false
  vars:
    backup_path: "/var/lib/awx/projects/su_network_backup/kantra/building_A/stack"

  tasks:
    - name: Create backup directory if it doesn't exist
      file:
        path: "{{ backup_path }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: yes

    - name: Backup Cisco IOS switch configurations
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: "{{ backup_path }}"
      register: backup_results

# No Git operations in the main playbook
# Instead, create a post-job command in AWX job template
